#!/usr/bin/env bash


# Directories
alias Transcend="cd /media/undefined/Transcend"
alias Works="cd /media/undefined/Works"
alias Nexify="cd /media/undefined/Works/Codes\ and\ Projects/Javascript/React/practice/nexify/"
alias Techdiary="cd /media/undefined/Works/Codes\ and\ Projects/Open\ Source/kingRayhan/Tech\ Diary/"
alias Pwebsite="cd /media/undefined/Works/Codes\ and\ Projects/Personal/ittisafur.com/"
alias Streetlife="cd /media/undefined/Works/Clients/fiverr/streetlifelabs/landing/"
alias Raush="cd /media/undefined/Works/Clients/Raush/landing/"
alias Rental="cd /media/undefined/Works/Clients/DipRaihan/rental-client/"
alias Protoconn="cd /media/undefined/Works/Clients/Protoconn/webapp/"
alias Chriss="cd /media/undefined/Works/Clients/chriss/banana-club/"
alias NodeJonas="cd /media/undefined/Works/Codes\ and\ Projects/Javascript/Node/Jonas"
alias Ytp="pipe-viewer -n --no-video --player=mpvt"


# Manage dotfiles
alias Dfs=$HOME/dotfiles/

