#!/usr/bin/env bash


# Directories
alias Transcend="cd /media/undefined/Transcend"
alias Works="cd /media/undefined/Works"
alias Nexify="cd /media/undefined/Works/Codes\ and\ Projects/Javascript/React/practice/nexify/"
alias Techdiary="cd /media/undefined/Works/Codes\ and\ Projects/Open\ Source/kingRayhan/Tech\ Diary/"
alias Node="cd /media/undefined/Works/Codes\ and\ Projects/Node"
alias Nest="cd /media/undefined/Works/Codes\ and\ Projects/Javascript/Nest"
alias Pwebsite="cd /media/undefined/Works/Codes\ and\ Projects/Personal/ittisafur.com/"
alias Jpegdegens="cd /media/undefined/Works/Codes\ and\ Projects/Blockchain/FEM\ -\ Blockchain/jpegdegens/"
alias TypeScript="cd /media/undefined/Works/Codes\ and\ Projects/TypeScript/"
alias Movieapp="cd /media/undefined/Works/Codes\ and\ Projects/Javascript/React/Next/movie-app"
alias Redux="cd /media/undefined/Works/Codes\ and\ Projects/Redux/"
alias Rust="cd /media/undefined/Works/Codes\ and\ Projects/Rust/"
alias Flutter="cd /media/undefined/Works/Codes\ and\ Projects/Flutter/"
alias Laravel="cd /media/undefined/Works/Codes\ and\ Projects/Laravel"
alias Shopify="cd /media/undefined/Works/Codes\ and\ Projects/Shopify/"
alias Shopify="cd /media/undefined/Works/Codes\ and\ Projects/Wordpress/"
alias Raush="cd /media/undefined/Works/Clients/Raush/"
alias Protoconn="cd /media/undefined/Works/Clients/Protoconn/webapp/"
alias Chriss="cd /media/undefined/Works/Clients/chriss/banana-club/"
alias Lasogette="cd /media/undefined/Works/Clients/Bloopy/dama/lasogette/"
alias Neudevinc="cd /media/undefined/Works/Clients/Neudevinc/Recast/"
alias Recast="cd /media/undefined/Works/Clients/Recast/Recast/"
alias Kanarys="cd ~/Works/Kanarys/"
alias NodeJonas="cd /media/undefined/Works/Codes\ and\ Projects/Javascript/Node/jonas"
alias React="cd /media/undefined/Works/Codes\ and\ Projects/Javascript/React"
alias Wordpress="cd /media/undefined/Works/Codes\ and\ Projects/Wordpress"
alias Ytp="pipe-viewer -n --no-video --player=mpvt"


# Manage dotfiles
alias DFS=$HOME/dotfiles/

# Lvim configuration
alias lvimrc="lvim $HOME/.config/lvim/config.lua"

# Nvim configuration

# Update and Upgrade Packages
alias upupgrade="sudo apt-get update && sudo apt-get upgrade"

